# Generated by Django 5.1.6 on 2026-04-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='apdated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
