# Generated by Django 5.1.6 on 2026-04-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0002_subscription_apdated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='apdated_at',
        ),
    ]
