# Generated by Django 5.1.6 on 2026-04-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0003_remove_subscription_apdated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='trial_start_date',
        ),
    ]
