# Generated by Django 5.1.6 on 2026-04-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0004_remove_club_trial_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='trial_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
