# Generated by Django 5.1.6 on 2026-04-13 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0005_club_trial_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='status',
        ),
    ]
