# Generated by Django 5.1.6 on 2026-04-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0006_remove_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('trialing', 'Trialing'), ('pending', 'Pending')], default='active', max_length=20),
            preserve_default=False,
        ),
    ]
