# Generated by Django 5.1.6 on 2026-04-13 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0007_subscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='pdated_at',
        ),
    ]
