# Generated by Django 5.1.6 on 2026-04-13 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0008_remove_subscription_pdated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='last_invoice_id',
        ),
    ]
