# Generated by Django 5.1.6 on 2026-04-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0009_remove_subscription_last_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
