# Generated by Django 5.1.6 on 2026-04-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0010_subscription_last_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='has_paid_joining_fee',
        ),
    ]
