# Generated by Django 5.1.6 on 2026-04-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0011_remove_member_has_paid_joining_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='has_paid_joining_fee',
            field=models.BooleanField(default=False),
        ),
    ]
