# Generated by Django 5.1.6 on 2026-04-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0012_member_has_paid_joining_fee'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscriptionitem',
            constraint=models.UniqueConstraint(fields=('subscription', 'member'), name='unique_member_per_subscription'),
        ),
    ]
