# Generated by Django 5.1.6 on 2026-04-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0013_subscriptionitem_unique_member_per_subscription'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptionitem',
            name='unique_member_per_subscription',
        ),
        migrations.AddConstraint(
            model_name='subscriptionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('plan__isnull', False)), fields=('subscription', 'member', 'plan'), name='unique_member_plan_per_subscription'),
        ),
    ]
