# Generated by Django 5.1.6 on 2026-04-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0015_alter_member_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='has_been_charged_joining_fee',
            field=models.BooleanField(default=False),
        ),
    ]
