# Generated by Django 5.1.6 on 2026-04-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0017_stripecustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
