# Generated by Django 5.1.6 on 2026-04-19 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0018_alter_club_stripe_account_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stripecustomer',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='stripecustomer',
            constraint=models.UniqueConstraint(fields=('user', 'club'), name='unique_stripe_customer_per_user_club'),
        ),
    ]
