# Generated by Django 5.1.6 on 2026-04-19 02:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0019_alter_stripecustomer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
