# Generated by Django 5.1.6 on 2026-04-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0020_stripecustomer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionitem',
            name='price_at_subscription',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='stripe_price_id_at_subscription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
