# Generated by Django 5.1.6 on 2026-04-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0021_subscriptionitem_price_at_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='apply_to',
            field=models.CharField(choices=[('subscription', 'Monthly subscription'), ('joining_fee', 'Joining fee')], default='subscription', max_length=20),
        ),
    ]
