# Generated by Django 5.1.6 on 2026-05-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0022_discount_apply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='counts_for_family_discount',
            field=models.BooleanField(default=True, help_text='Whether this member counts toward family discount calculations'),
        ),
    ]
