# Generated by Django 5.1.6 on 2026-05-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0023_member_counts_for_family_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcondition',
            name='type',
            field=models.CharField(choices=[('gender', 'Gender'), ('age_lt', 'Age <'), ('age_gt', 'Age >'), ('is_family', 'Family group')], max_length=50),
        ),
    ]
