# Generated by Django 5.1.6 on 2026-05-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0024_alter_discountcondition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='plans',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='kaibaru.membershipplan'),
        ),
    ]
