# Generated by Django 5.1.6 on 2026-05-11 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0025_discount_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='kaibaru.club'),
        ),
    ]
