# Generated by Django 5.1.6 on 2026-05-15 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0026_alter_discount_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPricingAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', '%'), ('fixed', '¥')], max_length=20)),
                ('value', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_pricing_adjustments', to='kaibaru.club')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_adjustments', to='kaibaru.member')),
            ],
        ),
    ]
