# Generated by Django 5.1.6 on 2026-05-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0027_memberpricingadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpricingadjustment',
            name='plans',
            field=models.ManyToManyField(blank=True, related_name='member_adjustments', to='kaibaru.membershipplan'),
        ),
    ]
