# Generated by Django 5.1.6 on 2026-05-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0028_memberpricingadjustment_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='bundled_plans',
            field=models.ManyToManyField(blank=True, related_name='part_of_bundles', to='kaibaru.membershipplan'),
        ),
    ]
