# Generated by Django 5.1.6 on 2026-05-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0029_membershipplan_bundled_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionitem',
            name='access_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='plan_change_locked',
            field=models.BooleanField(default=False),
        ),
    ]
