# Generated by Django 5.1.6 on 2026-05-25 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0030_subscriptionitem_access_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionitem',
            name='source_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_for', to='kaibaru.subscriptionitem'),
        ),
    ]
