# Generated by Django 5.1.6 on 2026-05-26 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0031_subscriptionitem_source_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlanGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaibaru.club')),
                ('default_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_groups', to='kaibaru.membershipplan')),
            ],
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='kaibaru.membershipplangroup'),
        ),
    ]
