# Generated by Django 5.1.6 on 2026-05-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0032_membershipplangroup_membershipplan_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
