# Generated by Django 5.1.6 on 2026-06-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0033_membershipplan_deleted_at_membershipplan_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
