# Generated by Django 5.1.6 on 2026-06-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0034_subscription_billing_lock_until'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptionitem',
            name='unique_member_plan_per_subscription',
        ),
        migrations.AddConstraint(
            model_name='subscriptionitem',
            constraint=models.UniqueConstraint(fields=('subscription', 'member', 'plan'), name='unique_member_plan_per_subscription'),
        ),
    ]
