# Generated by Django 5.1.6 on 2026-06-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0035_remove_subscriptionitem_unique_member_plan_per_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionitem',
            name='cancel_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='change_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
