# Generated by Django 5.1.6 on 2026-06-25 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0036_subscriptionitem_cancel_locked_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionitem',
            name='quantity',
        ),
    ]
