# Generated by Django 5.1.6 on 2026-06-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0037_remove_subscriptionitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionitem',
            name='intent',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
