# Generated by Django 5.1.6 on 2026-06-29 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0038_subscriptionitem_intent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionMutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cancel', 'Cancel item'), ('resume', 'Resume item'), ('change_plan', 'Change plan')], max_length=32)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('stripe_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutations', to='kaibaru.subscriptionitem')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutations', to='kaibaru.subscription')),
            ],
            options={
                'indexes': [models.Index(fields=['subscription', 'status'], name='kaibaru_sub_subscri_25eb90_idx'), models.Index(fields=['created_at'], name='kaibaru_sub_created_913438_idx')],
            },
        ),
    ]
