# Generated by Django 5.1.6 on 2026-07-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0039_subscriptionmutation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionitem',
            name='intent',
        ),
    ]
