# Generated by Django 5.1.6 on 2026-07-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0040_remove_subscriptionitem_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmutation',
            name='secondary_mutation_blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
