# Generated by Django 5.1.6 on 2026-07-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0041_subscriptionmutation_secondary_mutation_blocked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmutation',
            name='type',
            field=models.CharField(choices=[('cancel', 'Cancel item'), ('resume', 'Resume item'), ('change_plan', 'Change plan'), ('cancel_change_plan', 'Cancel plan change')], max_length=32),
        ),
    ]
