# Generated by Django 5.1.6 on 2026-07-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0042_alter_subscriptionmutation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionitem',
            name='cancel_locked_until',
        ),
        migrations.RemoveField(
            model_name='subscriptionitem',
            name='change_locked_until',
        ),
    ]
