# Generated by Django 5.1.6 on 2026-07-06 03:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0043_remove_subscriptionitem_cancel_locked_until_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentmethod',
            name='one_default_payment_method_per_member',
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='one_active_subscription_per_owner_club',
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('member',), name='one_default_payment_method_per_member'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('owner', 'club'), name='one_active_subscription_per_owner_club'),
        ),
    ]
