# Generated by Django 5.1.6 on 2026-07-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0044_remove_paymentmethod_one_default_payment_method_per_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmutation',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not started'), ('retry', 'Retry required'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default=None, max_length=20, null=True),
        ),
    ]
