# Generated by Django 5.1.6 on 2026-07-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0045_subscriptionmutation_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmutation',
            name='type',
            field=models.CharField(choices=[('cancel', 'Cancel item'), ('resume', 'Resume item'), ('change_plan', 'Change plan'), ('cancel_change_plan', 'Cancel plan change'), ('add_plan', 'Add plan')], max_length=32),
        ),
    ]
