# Generated by Django 5.1.6 on 2026-07-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0046_alter_subscriptionmutation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripewebhookevent',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stripewebhookevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stripewebhookevent',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
    ]
