# Generated by Django 5.1.6 on 2026-07-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0047_stripewebhookevent_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripewebhookevent',
            name='needs_reconciliation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stripewebhookevent',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='needs_reconciliation',
            field=models.BooleanField(default=False),
        ),
    ]
