# Generated by Django 5.1.6 on 2026-07-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0048_stripewebhookevent_needs_reconciliation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmutation',
            name='can_resume_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
