# Generated by Django 5.1.6 on 2026-07-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0049_subscriptionmutation_can_resume_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='apply_current_price_to_existing',
            field=models.BooleanField(default=False, help_text='If enabled, existing members will be charged the current plan price instead of their subscription price.'),
        ),
    ]
