# Generated by Django 5.1.6 on 2026-07-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0050_membershipplan_apply_current_price_to_existing'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('manual', 'Manual')], default='stripe', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
