# Generated by Django 5.1.6 on 2026-07-29 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0051_subscription_billing_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='member',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='member',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kaibaru.member'),
        ),
    ]
