# Generated by Django 5.1.6 on 2026-07-29 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0053_invoice_payer_invoice_payer_email_invoice_payer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='mutation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='kaibaru.subscriptionmutation'),
        ),
    ]
