# Generated by Django 5.1.6 on 2026-01-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0055_slateimage_unique_slate_image_per_club_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='page_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
