# Generated by Django 5.1.6 on 2026-07-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0055_alter_invoice_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
