# Generated by Django 5.1.6 on 2026-02-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0056_club_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='section_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
