# Generated by Django 5.1.6 on 2026-08-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0056_alter_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_reason',
            field=models.CharField(blank=True, choices=[('initial_subscription', 'Initial subscription'), ('subscription_cycle', 'Subscription cycle'), ('add_plan', 'Add plan')], max_length=50, null=True),
        ),
    ]
