# Generated by Django 5.1.6 on 2026-02-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0057_lesson_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='section_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
