# Generated by Django 5.1.6 on 2026-08-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0057_invoice_billing_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='already_subscribed_plans',
            field=models.ManyToManyField(blank=True, related_name='legacy_join_requests', to='kaibaru.membershipplan'),
        ),
    ]
