# Generated by Django 5.1.6 on 2026-02-20 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0058_alter_lesson_section_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='join_key',
        ),
    ]
