# Generated by Django 5.1.6 on 2026-08-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0059_invoice_billing_cycle_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmutation',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('open', 'Invoice open'), ('not_started', 'Not started'), ('retry', 'Retry required'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default=None, max_length=20, null=True),
        ),
    ]
