# Generated by Django 5.1.6 on 2026-02-26 08:25

import kaibaru.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0060_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='contract',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='emergency_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='furigana',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='member_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='other_information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=kaibaru.models.club_member_pictures_upload_to),
        ),
    ]
