# Generated by Django 5.1.6 on 2026-02-28 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0061_joinrequest_contract_joinrequest_emergency_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='joinrequest',
            name='kaibaru_joi_club_id_53d8c0_idx',
        ),
        migrations.RemoveField(
            model_name='joinrequest',
            name='status',
        ),
        migrations.AddIndex(
            model_name='joinrequest',
            index=models.Index(fields=['club'], name='kaibaru_joi_club_id_4fd287_idx'),
        ),
    ]
