# Generated by Django 5.1.6 on 2026-08-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0061_invoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='original_payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('cash', 'Cash'), ('bank_transfer', 'Bank transfer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
