# Generated by Django 5.1.6 on 2026-03-04 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0062_remove_joinrequest_kaibaru_joi_club_id_53d8c0_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'ordering': ['price_cents']},
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_plans', to='kaibaru.club'),
        ),
    ]
