# Generated by Django 5.1.6 on 2026-08-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0062_invoice_original_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='original_payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('cash', 'Cash'), ('bank_transfer', 'Bank transfer')], default='cash', max_length=20),
        ),
    ]
