# Generated by Django 5.1.6 on 2026-03-05 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0063_alter_membershipplan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'ordering': ['price']},
        ),
        migrations.RenameField(
            model_name='membershipplan',
            old_name='price_cents',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='onetimeproduct',
            old_name='price_cents',
            new_name='price',
        ),
    ]
