# Generated by Django 5.1.6 on 2026-08-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0063_alter_invoice_original_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
