# Generated by Django 5.1.6 on 2026-08-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0064_invoice_stripe_payment_failed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_cash_transition_status',
            field=models.CharField(blank=True, choices=[('started', 'Started'), ('succeeded', 'Succeeded')], max_length=20, null=True),
        ),
    ]
