# Generated by Django 5.1.6 on 2026-03-05 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0064_alter_membershipplan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_type',
        ),
    ]
