# Generated by Django 5.1.6 on 2026-08-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0065_invoice_stripe_cash_transition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_cash_transition_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
