# Generated by Django 5.1.6 on 2026-03-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0065_remove_member_contract_remove_member_member_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinrequest',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='joinrequest',
            name='member_type',
        ),
    ]
