# Generated by Django 5.1.6 on 2026-08-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0066_invoice_stripe_cash_transition_email_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='stripe_cash_transition_email_sent',
            new_name='stripe_cash_member_email_sent',
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_cash_owner_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
