# Generated by Django 5.1.6 on 2026-08-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0067_rename_stripe_cash_transition_email_sent_invoice_stripe_cash_member_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_failure_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
