# Generated by Django 5.1.6 on 2026-08-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0068_invoice_stripe_payment_failure_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmutation',
            name='local_state_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionmutation',
            name='stripe_reconciliation_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionmutation',
            name='type',
            field=models.CharField(choices=[('cancel', 'Cancel item'), ('resume', 'Resume item'), ('change_plan', 'Change plan'), ('cancel_change_plan', 'Cancel plan change'), ('add_plan', 'Add plan'), ('cash_to_stripe', 'Cash to Stripe')], max_length=32),
        ),
    ]
