# Generated by Django 5.1.6 on 2026-03-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0068_subscriptionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('trialing', 'Trialing'), ('pending', 'Pending')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'trialing', 'pending'])), fields=('member',), name='one_active_subscription_per_member'),
        ),
    ]
