# Generated by Django 5.1.6 on 2026-08-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0069_subscriptionmutation_local_state_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_status_checked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
