# Generated by Django 5.1.6 on 2026-03-05 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0070_invoice_invoiceitem_payment_paymentmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='created_at',
            new_name='issued_at',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='issued_at',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='club',
            field=models.ForeignKey(default=115, on_delete=django.db.models.deletion.CASCADE, to='kaibaru.club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='club',
            field=models.ForeignKey(default=115, on_delete=django.db.models.deletion.CASCADE, to='kaibaru.club'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('member',), name='one_default_payment_method_per_member'),
        ),
    ]
