# Generated by Django 5.1.6 on 2026-08-31 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0070_subscription_stripe_status_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='allowed_plans',
            field=models.ManyToManyField(blank=True, related_name='allowed_lessons', to='kaibaru.membershipplan'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='カラーは #FFFFFF の形式で指定してください。', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
