# Generated by Django 5.1.6 on 2026-09-02 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0071_lesson_allowed_plans_lesson_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='trial_price',
            field=models.PositiveIntegerField(default=0, help_text='Default trial reservation price. 0 means free.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='one_time_price',
            field=models.PositiveIntegerField(blank=True, help_text='One-time visitor reservation price. Empty means unavailable.', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='reservation_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of reservations. Leave empty for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='reservation_only',
            field=models.BooleanField(default=False, help_text='If enabled, this lesson can only be booked through a reservation.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='trial_disabled',
            field=models.BooleanField(default=False, help_text='If enabled, trial reservations are not allowed.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='trial_price',
            field=models.PositiveIntegerField(blank=True, help_text='Trial price for this lesson. Empty uses the club default.', null=True),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_type', models.CharField(choices=[('trial', 'Trial'), ('visitor', 'Visitor')], max_length=20)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='jpy', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='kaibaru.club')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='kaibaru.lesson')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='kaibaru.member')),
            ],
            options={
                'indexes': [models.Index(fields=['lesson', 'status'], name='kaibaru_res_lesson__b0c37c_idx'), models.Index(fields=['club', 'created_at'], name='kaibaru_res_club_id_15ab19_idx')],
            },
        ),
    ]
