# Generated by Django 5.1.6 on 2026-03-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0071_rename_created_at_invoice_issued_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
