# Generated by Django 5.1.6 on 2026-09-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0072_club_trial_price_lesson_one_time_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='trials_disabled',
            field=models.BooleanField(default=False, help_text='If enabled, trial reservations are unavailable for all lessons.'),
        ),
    ]
