# Generated by Django 5.1.6 on 2026-03-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0072_subscription_last_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_customer_id',
        ),
        migrations.AddField(
            model_name='member',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
