# Generated by Django 5.1.6 on 2026-09-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0073_club_trials_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='only_plans',
            field=models.BooleanField(default=False, help_text='Only members with one of the allowed plans can access this lesson.'),
        ),
    ]
