# Generated by Django 5.1.6 on 2026-03-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0073_remove_subscription_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='subscription_cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='subscription_current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
