# Generated by Django 5.1.6 on 2026-09-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0074_lesson_only_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
