# Generated by Django 5.1.6 on 2026-03-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0074_club_subscription_cancel_at_period_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
