# Generated by Django 5.1.6 on 2026-03-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0075_alter_club_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='stripe_anchor_date',
            field=models.DateField(blank=True, help_text='If set, subscriptions will align to this day of the month', null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='subscription_mode',
            field=models.CharField(choices=[('monthly', '月謝 (fixed monthly)'), ('regular', 'Regular subscription')], default='regular', help_text='Whether the club uses fixed monthly billing or regular subscription mode', max_length=20),
        ),
    ]
