# Generated by Django 5.1.6 on 2026-03-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0076_club_stripe_anchor_date_club_subscription_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='stripe_anchor_date',
            field=models.PositiveSmallIntegerField(blank=True, help_text='If set, subscriptions will align to this day of the month (1-28)', null=True),
        ),
    ]
