# Generated by Django 5.1.6 on 2026-09-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0076_reservation_stripe_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
