# Generated by Django 5.1.6 on 2026-09-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0077_alter_reservation_reservation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='one_time_price',
        ),
        migrations.AddField(
            model_name='club',
            name='member_reservation_price',
            field=models.PositiveIntegerField(blank=True, help_text='Default member reservation price. Empty means unavailable.', null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='member_reservations_disabled',
            field=models.BooleanField(default=False, help_text='If enabled, member reservations are unavailable for all lessons.'),
        ),
        migrations.AddField(
            model_name='club',
            name='visitor_reservation_price',
            field=models.PositiveIntegerField(blank=True, help_text='Default visitor reservation price. Empty means unavailable.', null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='visitor_reservations_disabled',
            field=models.BooleanField(default=False, help_text='If enabled, visitor reservations are unavailable for all lessons.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='member_reservation_disabled',
            field=models.BooleanField(default=False, help_text='If enabled, member reservations are not allowed for this lesson.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='member_reservation_price',
            field=models.PositiveIntegerField(blank=True, help_text='Member reservation price. Empty uses the club default.', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='visitor_reservation_disabled',
            field=models.BooleanField(default=False, help_text='If enabled, visitor reservations are not allowed for this lesson.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='visitor_reservation_price',
            field=models.PositiveIntegerField(blank=True, help_text='Visitor reservation price. Empty uses the club default.', null=True),
        ),
    ]
