# Generated by Django 5.1.6 on 2026-03-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0077_alter_club_stripe_anchor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_anchor_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Anchor day used for this subscription (1-28)', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_mode',
            field=models.CharField(choices=[('monthly', 'Fixed monthly'), ('regular', 'Regular')], default='regular', max_length=20),
        ),
    ]
