# Generated by Django 5.1.6 on 2026-09-04 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0078_remove_lesson_one_time_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='only_plans',
        ),
    ]
