# Generated by Django 5.1.6 on 2026-03-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0078_subscription_billing_anchor_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='stripe_anchor_date',
            field=models.PositiveSmallIntegerField(blank=True, default=25, help_text='If set, subscriptions will align to this day of the month (1-28)', null=True),
        ),
    ]
