# Generated by Django 5.1.6 on 2026-09-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0079_remove_lesson_only_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
