# Generated by Django 5.1.6 on 2026-03-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0080_stripewebhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='joining_fee',
            field=models.IntegerField(default=0, help_text='入会金 (one-time fee charged when a member joins)'),
        ),
    ]
