# Generated by Django 5.1.6 on 2026-03-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0081_club_joining_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
