# Generated by Django 5.1.6 on 2026-09-10 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0081_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_type',
            field=models.CharField(choices=[('trial', 'Trial'), ('visitor', 'Visitor'), ('member', 'Member')], max_length=20),
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='kaibaru.club')),
                ('eligible_plans', models.ManyToManyField(blank=True, related_name='ticket_types', to='kaibaru.membershipplan')),
            ],
        ),
        migrations.CreateModel(
            name='TicketPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('currency', models.CharField(default='jpy', max_length=10)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_packages', to='kaibaru.club')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='kaibaru.tickettype')),
            ],
        ),
        migrations.CreateModel(
            name='TicketGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('purchase', 'Purchase'), ('manual', 'Manual')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_grants', to='kaibaru.member')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='kaibaru.ticketpackage')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='kaibaru.tickettype')),
            ],
        ),
        migrations.CreateModel(
            name='TicketUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='kaibaru.ticketgrant')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_usage', to='kaibaru.reservation')),
            ],
        ),
    ]
