# Generated by Django 5.1.6 on 2026-03-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0082_membershipplan_stripe_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='stripe_anchor_date',
            field=models.PositiveSmallIntegerField(blank=True, default=25, help_text='If set, subscriptions will align to this day of the month (2-27)', null=True),
        ),
    ]
