# Generated by Django 5.1.6 on 2026-09-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0082_alter_reservation_reservation_type_tickettype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpackage',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
