# Generated by Django 5.1.6 on 2026-03-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0083_alter_club_stripe_anchor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionitem',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
