# Generated by Django 5.1.6 on 2026-03-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0084_subscriptionitem_cancel_at_period_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionitem',
            name='cancel_at_period_end',
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
