# Generated by Django 5.1.6 on 2026-09-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0084_ticketpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('ticket', 'Ticket')], max_length=20, null=True),
        ),
    ]
