# Generated by Django 5.1.6 on 2026-09-14 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0085_reservation_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='plan_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('ticket_plan', 'Ticket plan'), ('bundle', 'Bundle')], db_index=True, default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='ticket_expiration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='ticket_expiration_mode',
            field=models.CharField(choices=[('end_of_month', 'End of month'), ('never', 'Never'), ('days_after_grant', 'Days after grant')], default='end_of_month', max_length=30),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='ticket_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_plans', to='kaibaru.tickettype'),
        ),
    ]
