# Generated by Django 5.1.6 on 2026-03-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0085_remove_subscriptionitem_cancel_at_period_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionitem',
            name='stripe_subscription_item_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
