# Generated by Django 5.1.6 on 2026-03-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0086_alter_subscriptionitem_stripe_subscription_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='access_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
