# Generated by Django 5.1.6 on 2026-09-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0087_alter_membershipplan_ticket_expiration_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketgrant',
            name='source',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('manual', 'Manual'), ('subscription', 'Subscription')], max_length=20),
        ),
    ]
