# Generated by Django 5.1.6 on 2026-04-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0087_subscription_access_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='stripe_anchor_date',
            field=models.PositiveSmallIntegerField(default=25, help_text='If set, subscriptions will align to this day of the month (2-27)'),
        ),
    ]
