# Generated by Django 5.1.6 on 2026-09-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0088_alter_ticketgrant_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketgrant',
            name='stripe_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
