# Generated by Django 5.1.6 on 2026-04-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0088_alter_club_stripe_anchor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='billing_anchor_day',
            field=models.PositiveSmallIntegerField(default='25', help_text='Anchor day used for this subscription (1-28)'),
        ),
    ]
