# Generated by Django 5.1.6 on 2026-09-20 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0089_ticketgrant_stripe_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketgrant',
            name='subscription_mutation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_grants', to='kaibaru.subscriptionmutation'),
        ),
    ]
