# Generated by Django 5.1.6 on 2026-04-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0089_alter_subscription_billing_anchor_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionitem',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
