# Generated by Django 5.1.6 on 2026-09-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0090_ticketgrant_subscription_mutation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketgrant',
            old_name='subscription_mutation',
            new_name='mutation',
        ),
        migrations.AddConstraint(
            model_name='ticketgrant',
            constraint=models.UniqueConstraint(fields=('mutation',), name='unique_ticket_grant_per_subscription_mutation'),
        ),
    ]
