# Generated by Django 5.1.6 on 2026-04-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0090_subscriptionitem_cancel_at_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='has_paid_joining_fee',
            field=models.BooleanField(default=False),
        ),
    ]
