# Generated by Django 5.1.6 on 2026-04-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0091_club_has_paid_joining_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionitem',
            name='access_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
