# Generated by Django 5.1.6 on 2026-09-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0091_rename_subscription_mutation_ticketgrant_mutation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='scheduled_for_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
