# Generated by Django 5.1.6 on 2026-09-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0092_membershipplan_scheduled_for_deletion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='max_lessons_per_month',
        ),
        migrations.RemoveField(
            model_name='membershipplan',
            name='member_category',
        ),
        migrations.AddField(
            model_name='lesson',
            name='age_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='age_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='allowed_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='If set, only this gender may reserve. Empty means any gender.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='allowed_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='If set, only this gender may join. Empty means any gender.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
