# Generated by Django 5.1.6 on 2026-04-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0092_subscriptionitem_access_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionitem',
            name='monthly_double_resume_charge_prevention',
            field=models.BooleanField(default=False),
        ),
    ]
