# Generated by Django 5.1.6 on 2026-09-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0093_remove_membershipplan_max_lessons_per_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='member_reservation_max_count',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum upcoming member reservations per member. Empty means unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='member_reservation_max_days_ahead',
            field=models.PositiveIntegerField(blank=True, help_text='How many days ahead a member may reserve. Empty means no date horizon. 0 means today only.', null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='visitor_reservation_max_count',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum upcoming visitor reservations per email. Empty means unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='visitor_reservation_max_days_ahead',
            field=models.PositiveIntegerField(blank=True, help_text='How many days ahead a visitor may reserve. Empty means no date horizon. 0 means today only.', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='member_reservation_max_count',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum upcoming member reservations for this lesson. Empty means no extra lesson cap.', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='member_reservation_max_days_ahead',
            field=models.PositiveIntegerField(blank=True, help_text='How many days ahead a member may reserve this lesson. Empty uses the club setting.', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='visitor_reservation_max_count',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum upcoming visitor reservations for this lesson per email. Empty means no extra lesson cap.', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='visitor_reservation_max_days_ahead',
            field=models.PositiveIntegerField(blank=True, help_text='How many days ahead a visitor may reserve this lesson. Empty uses the club setting.', null=True),
        ),
    ]
