# Generated by Django 5.1.6 on 2026-09-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0094_club_member_reservation_max_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checkout_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='club',
            name='member_reservation_max_count',
            field=models.PositiveIntegerField(blank=True, help_text='Default maximum upcoming member reservations per member per lesson. Empty means unlimited. Lessons may override.', null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='visitor_reservation_max_count',
            field=models.PositiveIntegerField(blank=True, help_text='Default maximum upcoming visitor reservations per email per lesson. Empty means unlimited. Lessons may override.', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='member_reservation_max_count',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum upcoming member reservations for this lesson. Empty uses the club setting.', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='visitor_reservation_max_count',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum upcoming visitor reservations for this lesson per email. Empty uses the club setting.', null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('not_started', 'Not started')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
