# Generated by Django 5.1.6 on 2026-04-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0095_alter_member_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
