# Generated by Django 5.1.6 on 2026-09-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0095_reservation_checkout_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='trial_staff_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
