# Generated by Django 5.1.6 on 2026-04-06 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0096_joinrequest_birth_date_joinrequest_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000, 5, 4)),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000, 5, 4)),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
    ]
