# Generated by Django 5.1.6 on 2026-09-24 01:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0096_reservation_trial_staff_email_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.IntegerField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('picture', models.CharField(blank=True, default='', max_length=1000)),
                ('starts_at', models.DateTimeField()),
                ('member_price', models.PositiveIntegerField(blank=True, help_text='Member price in yen. Empty means free.', null=True)),
                ('visitor_price', models.PositiveIntegerField(blank=True, help_text='Visitor price in yen. Empty means free.', null=True)),
                ('reservation_limit', models.PositiveIntegerField(blank=True, help_text='Maximum reservations. Empty means unlimited.', null=True)),
                ('audience', models.CharField(choices=[('members', 'Members'), ('visitors', 'Visitors'), ('both', 'Members and visitors')], default='both', max_length=20)),
                ('title_color', models.CharField(default='#1c1917', max_length=7, validators=[django.core.validators.RegexValidator(message='カラーは #FFFFFF の形式で指定してください。', regex='^#[0-9A-Fa-f]{6}$')])),
                ('description_color', models.CharField(default='#57534e', max_length=7, validators=[django.core.validators.RegexValidator(message='カラーは #FFFFFF の形式で指定してください。', regex='^#[0-9A-Fa-f]{6}$')])),
                ('detail_color', models.CharField(default='#44403c', max_length=7, validators=[django.core.validators.RegexValidator(message='カラーは #FFFFFF の形式で指定してください。', regex='^#[0-9A-Fa-f]{6}$')])),
                ('button_color', models.CharField(default='#1c1917', max_length=7, validators=[django.core.validators.RegexValidator(message='カラーは #FFFFFF の形式で指定してください。', regex='^#[0-9A-Fa-f]{6}$')])),
                ('button_text_color', models.CharField(default='#faf6f1', max_length=7, validators=[django.core.validators.RegexValidator(message='カラーは #FFFFFF の形式で指定してください。', regex='^#[0-9A-Fa-f]{6}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='kaibaru.club')),
            ],
        ),
        migrations.CreateModel(
            name='EventReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_type', models.CharField(choices=[('visitor', 'Visitor'), ('member', 'Member')], max_length=20)),
                ('payment_method', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('not_started', 'Not started')], default='unpaid', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='jpy', max_length=10)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('checkout_started_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation_key', models.CharField(max_length=255, unique=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reservations', to='kaibaru.club')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='kaibaru.event')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_reservations', to='kaibaru.member')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('club', 'section_id'), name='unique_event_per_section'),
        ),
        migrations.AddIndex(
            model_name='eventreservation',
            index=models.Index(fields=['event', 'status'], name='kaibaru_eve_event_i_aad017_idx'),
        ),
        migrations.AddIndex(
            model_name='eventreservation',
            index=models.Index(fields=['club', 'created_at'], name='kaibaru_eve_club_id_5bfcd8_idx'),
        ),
    ]
