# Generated by Django 5.1.6 on 2026-09-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0097_event_eventreservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreservation',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
