# Generated by Django 5.1.6 on 2026-09-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0098_eventreservation_canceled_reservation_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpackage',
            name='ticket_expiration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketpackage',
            name='ticket_expiration_mode',
            field=models.CharField(choices=[('one_month', 'One month'), ('never', 'Never'), ('days_after_grant', 'Days after grant')], default='one_month', max_length=30),
        ),
    ]
