# Generated by Django 5.1.6 on 2026-09-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0099_ticketpackage_ticket_expiration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='stripe_refund_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
