# Generated by Django 5.1.6 on 2026-09-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0100_reservation_refunded_at_reservation_stripe_refund_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreservation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
