# Generated by Django 5.1.6 on 2026-09-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0101_eventreservation_is_deleted_reservation_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='refund_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
