# Generated by Django 5.1.6 on 2026-10-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0102_reservation_refund_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='layout',
            field=models.CharField(choices=[('default', 'Default'), ('yoga', 'Yoga')], default='default', help_text='Public page look. Default uses the standard layout.', max_length=20),
        ),
    ]
