# Generated by Django 5.1.6 on 2026-10-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0103_club_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='layout',
            field=models.CharField(choices=[('default', 'Default'), ('yoga', 'Yoga'), ('striking', 'Striking')], default='default', help_text='Public page look. Default uses the standard layout.', max_length=20),
        ),
    ]
