# Generated by Django 5.1.6 on 2026-10-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0105_alter_club_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='layout',
            field=models.CharField(choices=[('default', 'Default'), ('yoga', 'Yoga'), ('striking', 'Striking'), ('bjj/grappling', 'BJJ/Grappling'), ('karate/judo/arts', 'Karate/Judo/Arts')], default='default', help_text='Public page look. Default uses the standard layout.', max_length=20),
        ),
    ]
