# Generated by Django 5.1.6 on 2026-10-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0111_alter_club_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='layout',
            field=models.CharField(choices=[('default', 'Default'), ('yoga', 'Yoga'), ('striking', 'Striking'), ('bjj/grappling', 'BJJ/Grappling'), ('karate/judo', 'Karate/Judo'), ('boxercise/fitness', 'Boxercise/Fitness'), ('regular_gym', 'Regular Gym'), ('cramschool', 'Cramschool'), ('eikaiwa_school', 'Eikaiwa School'), ('dance', 'Dance'), ('swimming', 'Swimming'), ('music', 'Music'), ('regular_sports', 'Regular Sports')], default='default', help_text='Public page look. Default uses the standard layout.', max_length=20),
        ),
    ]
