# Generated by Django 5.1.6 on 2026-10-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0112_alter_club_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='default_background_color',
            field=models.CharField(blank=True, help_text='Page background as #RRGGBB. Empty follows the layout preset. Any hex is allowed.', max_length=7, null=True),
        ),
    ]
