# Generated by Django 5.1.6 on 2026-10-05 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0113_club_default_background_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='member_price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='visitor_price',
        ),
        migrations.AddField(
            model_name='eventreservation',
            name='price_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.CreateModel(
            name='EventPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('amount', models.PositiveIntegerField(default=0, help_text='Price in yen. 0 means free.')),
                ('position', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='kaibaru.event')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
