# Generated by Django 5.1.6 on 2026-10-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0114_remove_event_member_price_remove_event_visitor_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreservation',
            name='refund_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventreservation',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventreservation',
            name='stripe_refund_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
