# Generated by Django 5.1.6 on 2026-10-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0117_remove_event_kind_remove_event_results_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='frozen_at',
            field=models.DateTimeField(blank=True, help_text='Set when the owner freezes the test, at least one hour after registration closes.', null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='reservations_open_until',
            field=models.DateTimeField(blank=True, help_text='Registration closes at this time. Start links stop working.', null=True),
        ),
    ]
