# Generated by Django 5.1.6 on 2026-10-06 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0118_test_frozen_at_test_reservations_open_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results_public', models.BooleanField(default=False, help_text='When off, only the owner sees every place. Each participant sees their own.')),
                ('reservations_open_until', models.DateTimeField(blank=True, null=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='kaibaru.event')),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveIntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='kaibaru.competition')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement', to='kaibaru.eventreservation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('competition', 'place'), name='unique_competition_place')],
            },
        ),
    ]
