# Generated by Django 5.1.6 on 2026-10-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0119_competition_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='frozen_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled freeze time. Registration locks once this time is reached. Must be at least one hour after reservations_open_until.', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='frozen_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled freeze time. Registration locks once this time is reached. Must be at least one hour after reservations_open_until.', null=True),
        ),
    ]
