# Generated by Django 5.1.6 on 2026-10-06 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0120_alter_competition_frozen_at_alter_test_frozen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrecord',
            name='kind',
            field=models.CharField(choices=[('test', 'Test'), ('individual_competition', 'Individual competition'), ('duel', 'Duel'), ('team_competition', 'Team competition'), ('individual_tournament', 'Individual tournament'), ('team_tournament', 'Team tournament')], default='test', max_length=32),
        ),
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results_public', models.BooleanField(default=False, help_text='When off, only the owner sees every match. Each participant sees their own match.')),
                ('reservations_open_until', models.DateTimeField(blank=True, null=True)),
                ('frozen_at', models.DateTimeField(blank=True, help_text='Scheduled freeze time. Registration locks once this time is reached. Must be at least one hour after reservations_open_until.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duel', to='kaibaru.event')),
            ],
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='kaibaru.duel')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_first', to='kaibaru.eventreservation')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_second', to='kaibaru.eventreservation')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairing_wins', to='kaibaru.eventreservation')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('duel', 'position'), name='unique_duel_pairing_position'), models.UniqueConstraint(fields=('first',), name='unique_pairing_first'), models.UniqueConstraint(fields=('second',), name='unique_pairing_second')],
            },
        ),
    ]
