# Generated by Django 5.1.6 on 2026-10-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0121_alter_memberrecord_kind_duel_pairing'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairing',
            name='drawn',
            field=models.BooleanField(default=False),
        ),
    ]
