# Generated by Django 5.1.6 on 2026-10-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0122_pairing_drawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairing',
            name='note',
            field=models.CharField(blank=True, default='', help_text='Optional reason the winner won, such as a finish or a no-show.', max_length=200),
        ),
    ]
