# Generated by Django 5.1.6 on 2026-10-07 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0123_pairing_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('position', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BracketEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='kaibaru.bracket')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_entry', to='kaibaru.eventreservation')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results_public', models.BooleanField(default=False, help_text='When off, only the owner sees every bracket. A participant sees the bracket they are in.')),
                ('reservations_open_until', models.DateTimeField(blank=True, null=True)),
                ('frozen_at', models.DateTimeField(blank=True, help_text='Scheduled freeze time. Registration locks once this time is reached. Must be at least one hour after reservations_open_until.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='kaibaru.event')),
            ],
        ),
        migrations.AddField(
            model_name='bracket',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='kaibaru.tournament'),
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='kaibaru.bracket')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_first', to='kaibaru.eventreservation')),
                ('second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_second', to='kaibaru.eventreservation')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_wins', to='kaibaru.eventreservation')),
            ],
            options={
                'ordering': ['round', 'position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='bracket',
            constraint=models.UniqueConstraint(fields=('tournament', 'position'), name='unique_tournament_bracket_position'),
        ),
        migrations.AddConstraint(
            model_name='tournamentmatch',
            constraint=models.UniqueConstraint(fields=('bracket', 'round', 'position'), name='unique_tournament_match_position'),
        ),
    ]
