# Generated by Django 5.1.6 on 2026-10-08 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaibaru', '0124_bracket_bracketentry_tournament_bracket_tournament_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DivisionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('place', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='eventprice',
            name='brackets',
            field=models.ManyToManyField(blank=True, related_name='prices', to='kaibaru.bracket'),
        ),
        migrations.AddField(
            model_name='memberrecord',
            name='bracket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_records', to='kaibaru.bracket'),
        ),
        migrations.AlterField(
            model_name='bracketentry',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_entries', to='kaibaru.eventreservation'),
        ),
        migrations.AlterField(
            model_name='memberrecord',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_records', to='kaibaru.eventreservation'),
        ),
        migrations.AddConstraint(
            model_name='bracketentry',
            constraint=models.UniqueConstraint(fields=('bracket', 'reservation'), name='unique_bracket_reservation'),
        ),
        migrations.AddField(
            model_name='division',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='kaibaru.competition'),
        ),
        migrations.AddField(
            model_name='eventprice',
            name='divisions',
            field=models.ManyToManyField(blank=True, related_name='prices', to='kaibaru.division'),
        ),
        migrations.AddField(
            model_name='memberrecord',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_records', to='kaibaru.division'),
        ),
        migrations.AddField(
            model_name='divisionentry',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='kaibaru.division'),
        ),
        migrations.AddField(
            model_name='divisionentry',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_entries', to='kaibaru.eventreservation'),
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.UniqueConstraint(fields=('competition', 'name'), name='unique_division_name'),
        ),
        migrations.AddConstraint(
            model_name='divisionentry',
            constraint=models.UniqueConstraint(fields=('division', 'reservation'), name='unique_division_entry'),
        ),
        migrations.AddConstraint(
            model_name='divisionentry',
            constraint=models.UniqueConstraint(fields=('division', 'place'), name='unique_division_place'),
        ),
    ]
