# Generated by Django 5.1.6 on 2026-04-13 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('ar', 'Ar')], default='a', max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('description', models.BooleanField(default=False)),
                ('question_list', models.JSONField(blank=True, default=dict)),
                ('write_answer', models.BooleanField(default=False)),
                ('first_letter', models.BooleanField(default=False)),
                ('second_letter', models.BooleanField(default=False)),
                ('third_letter', models.BooleanField(default=False)),
                ('last_letter', models.BooleanField(default=False)),
                ('double_object', models.BooleanField(default=False)),
                ('no_sound', models.BooleanField(default=False)),
                ('sound2', models.BooleanField(default=False)),
                ('sound3', models.BooleanField(default=False)),
                ('sound4', models.BooleanField(default=False)),
                ('picture2', models.BooleanField(default=False)),
                ('word2', models.BooleanField(default=False)),
                ('label', models.BooleanField(default=False)),
                ('japanese_option', models.BooleanField(default=False)),
                ('display_all', models.BooleanField(default=False)),
                ('sentence_order', models.BooleanField(default=False)),
                ('story_picture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('story_sound_url', models.URLField(blank=True, max_length=500, null=True)),
                ('full_story_sound_url', models.URLField(blank=True, max_length=500, null=True)),
                ('story', models.TextField(blank=True, null=True)),
                ('full_story', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('option_list', models.JSONField(blank=True, default=dict)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_voice', models.BooleanField(default=False)),
                ('ivar_voice', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('battle_permission', models.BooleanField(default=False)),
                ('students', models.ManyToManyField(blank=True, related_name='classrooms', to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('unchangeable', models.BooleanField(default=False)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='main.classroom')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='main.teacher'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_b', models.CharField(blank=True, max_length=200, null=True)),
                ('name_c', models.CharField(blank=True, max_length=200, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('picture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('sound_url', models.URLField(blank=True, max_length=500, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('score_multiplier', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(choices=[('japanese', 'Japanese'), ('english_5', 'English 5'), ('english_6', 'English 6'), ('jr_1', 'jr_1'), ('jr_2', 'jr_2'), ('jr_3', 'jr_3'), ('phonics', 'Phonics'), ('numbers', 'Numbers'), ('eiken', 'Eiken'), ('eiken4', 'Eiken4'), ('eiken3', 'Eiken3'), ('eiken_pre2', 'Eiken Pre 2'), ('eiken2', 'Eiken2')], default='phonics', max_length=20)),
                ('lesson_number', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('number_of_questions', models.PositiveIntegerField(default=10)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('creator', models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.test'),
        ),
        migrations.CreateModel(
            name='MaxScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('total_questions', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.test')),
            ],
        ),
    ]
