from django.contrib import admin
from .models import (
    Member,
    Club,
    Lesson,
    Participation,
    SlateImage,
    JoinRequest,
    MembershipPlan,
    OneTimeProduct,
    OneTimePayment,
    Subscription,
    SubscriptionItem,
    Invoice,
    InvoiceItem,
    Payment,
    PaymentMethod,
    StripeCustomer,
)

admin.site.register([
    Club,
    Member,
    Lesson,
    Participation,
    SlateImage,
    JoinRequest,
    MembershipPlan,
    OneTimeProduct,
    OneTimePayment,
    Subscription,
    SubscriptionItem,
    Invoice,
    InvoiceItem,
    Payment,
    PaymentMethod,
    StripeCustomer,
])